name: ysfh_final
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bordered_text: ^2.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.1.3
  just_audio: ^0.9.31
  just_audio_windows: ^0.2.0
  riverpod_annotation: ^1.1.1
  window_manager: ^0.3.0

dev_dependencies:
  build_runner: null
  custom_lint: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.21.1
  riverpod_generator: ^1.1.1
  riverpod_lint: null

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/sounds/

  fonts:
    - family: Calibri
      fonts:
        - asset: assets/calibri.ttf
          weight: 400
