name: sharp_sf12_projection_mapping
description: YSFH12th Projection Mapping Application
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_launcher_icons: ^0.11.0
  hooks_riverpod: ^2.1.3
  just_audio: ^0.9.31
  just_audio_windows: ^0.2.0
  riverpod_annotation: ^1.1.1
  url_launcher: ^6.1.10

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  pedantic_mono: ^1.21.1
  riverpod_generator: ^1.1.1
  riverpod_lint: ^1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/sounds/

  fonts:
    - family: Calibri
      fonts:
        - asset: assets/calibri.ttf
          weight: 400

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ysfh.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    background_color: "#4e54c8"
    theme_color: "#4e54c8"
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
